# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target '百思不得姐' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 百思不得姐
	pod "AFNetworking"
	pod "SDWebImage"
	pod "MJExtension"
    pod "SVProgressHUD"
    pod "MJRefresh"
    pod "DACircularProgress"

  target '百思不得姐Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '百思不得姐UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
